// Licensed under Elastic License 2.0
// See LICENSE.txt for details

package services

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/bytefreezer/goodies/log"
	"github.com/bytefreezer/query/config"
)

// SchemaExtractor extracts and caches schema from parquet files
type SchemaExtractor struct {
	config         *config.Config
	duckdbClient   *DuckDBClient
	datasetService *DatasetService
	cache          map[string]*SchemaCache // keyed by dataset_id
	mu             sync.RWMutex
}

// SchemaCache holds cached schema information
type SchemaCache struct {
	Columns    []ColumnInfo
	Partitions []string
	SamplePath string
	CachedAt   time.Time
}

// SchemaResponse is returned by the /schema endpoint
type SchemaResponse struct {
	DatasetID  string       `json:"dataset_id"`
	Columns    []ColumnInfo `json:"columns"`
	Partitions []string     `json:"partitions"`
	SamplePath string       `json:"sample_path"`
}

// NewSchemaExtractor creates a new schema extractor
func NewSchemaExtractor(cfg *config.Config, duckdb *DuckDBClient, datasetService *DatasetService) *SchemaExtractor {
	return &SchemaExtractor{
		config:         cfg,
		duckdbClient:   duckdb,
		datasetService: datasetService,
		cache:          make(map[string]*SchemaCache),
	}
}

// GetSchema returns the schema for a dataset, using cache if available
func (s *SchemaExtractor) GetSchema(ctx context.Context, tenantID, datasetID string) (*SchemaResponse, error) {
	cacheKey := tenantID + "/" + datasetID
	s.mu.RLock()
	if cached, ok := s.cache[cacheKey]; ok && time.Since(cached.CachedAt) < 5*time.Minute {
		defer s.mu.RUnlock()
		return &SchemaResponse{
			DatasetID:  datasetID,
			Columns:    cached.Columns,
			Partitions: cached.Partitions,
			SamplePath: cached.SamplePath,
		}, nil
	}
	s.mu.RUnlock()

	// Need to refresh cache
	return s.refreshSchema(ctx, tenantID, datasetID)
}

// refreshSchema extracts schema from _common_metadata file in S3
// This file is generated by packer and contains the pre-merged schema (source of truth)
func (s *SchemaExtractor) refreshSchema(ctx context.Context, tenantID, datasetID string) (*SchemaResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	cacheKey := tenantID + "/" + datasetID

	// Try to get schema from _common_metadata file first (source of truth)
	metadata, err := s.datasetService.GetCommonMetadata(ctx, tenantID, datasetID)
	if err != nil {
		log.Warnf("Failed to get _common_metadata for %s/%s: %v, falling back to recent file", tenantID, datasetID, err)

		// Fallback: Get schema from most recent parquet file
		return s.refreshSchemaFromRecentFile(ctx, tenantID, datasetID, cacheKey)
	}

	// Convert metadata schema to ColumnInfo format
	var columns []ColumnInfo
	for _, field := range metadata.Schema.Fields {
		columns = append(columns, ColumnInfo{
			Name: field.Name,
			Type: field.Type,
		})
	}

	// Detect partition columns
	partitions := detectPartitions(columns)

	// Build sample path for reference
	metadataPath := s.datasetService.GetMetadataPath(ctx, tenantID, datasetID)

	// Update cache
	s.cache[cacheKey] = &SchemaCache{
		Columns:    columns,
		Partitions: partitions,
		SamplePath: metadataPath,
		CachedAt:   time.Now(),
	}

	log.Infof("Schema extracted from _common_metadata for dataset %s: %d columns, %d partitions, %d files, %d rows",
		datasetID, len(columns), len(partitions), metadata.FileCount, metadata.NumRows)

	return &SchemaResponse{
		DatasetID:  datasetID,
		Columns:    columns,
		Partitions: partitions,
		SamplePath: metadataPath,
	}, nil
}

// refreshSchemaFromRecentFile is a fallback method that extracts schema from the most recent parquet file
func (s *SchemaExtractor) refreshSchemaFromRecentFile(ctx context.Context, tenantID, datasetID, cacheKey string) (*SchemaResponse, error) {
	// Get the most recent parquet files for this dataset
	recentFiles, err := s.datasetService.GetRecentFiles(ctx, tenantID, datasetID, 1)
	if err != nil || len(recentFiles) == 0 {
		return nil, fmt.Errorf("no parquet files found for dataset %s", datasetID)
	}

	s3Path := recentFiles[0].Path
	log.Infof("Extracting schema from recent file (fallback): %s", s3Path)

	columns, err := s.duckdbClient.GetParquetSchema(ctx, s3Path)
	if err != nil {
		return nil, fmt.Errorf("failed to extract schema: %w", err)
	}

	// Detect partition columns
	partitions := detectPartitions(columns)

	// Update cache
	s.cache[cacheKey] = &SchemaCache{
		Columns:    columns,
		Partitions: partitions,
		SamplePath: s3Path,
		CachedAt:   time.Now(),
	}

	log.Infof("Schema extracted for dataset %s (fallback): %d columns, %d partitions", datasetID, len(columns), len(partitions))

	return &SchemaResponse{
		DatasetID:  datasetID,
		Columns:    columns,
		Partitions: partitions,
		SamplePath: s3Path,
	}, nil
}

// FormatSchemaForPrompt formats the schema for LLM prompt injection
func (s *SchemaExtractor) FormatSchemaForPrompt(ctx context.Context, tenantID, datasetID string) (string, error) {
	schema, err := s.GetSchema(ctx, tenantID, datasetID)
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	sb.WriteString("Table: security_events\n")
	sb.WriteString("Columns:\n")

	for _, col := range schema.Columns {
		sb.WriteString(fmt.Sprintf("  - %s (%s)\n", col.Name, col.Type))
	}

	if len(schema.Partitions) > 0 {
		sb.WriteString(fmt.Sprintf("Partitions: %s\n", strings.Join(schema.Partitions, ", ")))
	}

	sb.WriteString(fmt.Sprintf("\nData location: %s\n", schema.SamplePath))

	return sb.String(), nil
}

// detectPartitions identifies likely partition columns based on naming conventions
func detectPartitions(columns []ColumnInfo) []string {
	partitionNames := []string{"date", "year", "month", "day", "hour", "partition"}
	var partitions []string

	for _, col := range columns {
		colLower := strings.ToLower(col.Name)
		for _, pName := range partitionNames {
			if colLower == pName || strings.HasSuffix(colLower, "_"+pName) {
				partitions = append(partitions, col.Name)
				break
			}
		}
	}

	return partitions
}
